In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
arr = np.random.randint(1,40,10)
arr

array([28, 16, 11,  6, 33,  9, 21,  5, 26, 23])

In [3]:
arr = np.where(arr%2 !=0, 0,arr)
arr

array([28, 16,  0,  6,  0,  0,  0,  0, 26,  0])

In [4]:
arr = arr.reshape(2,5)
arr

array([[28, 16,  0,  6,  0],
       [ 0,  0,  0, 26,  0]])

In [5]:
arr = arr.reshape(2,5)
arr

array([[28, 16,  0,  6,  0],
       [ 0,  0,  0, 26,  0]])

In [6]:
arr2 = np.random.randint(1,40,16)
arr2

array([31,  6, 30, 30, 30, 37, 18,  3,  6,  5,  7, 26,  3, 34, 30, 11])

In [7]:
arr2 = arr2.reshape(4,4)
arr2

array([[31,  6, 30, 30],
       [30, 37, 18,  3],
       [ 6,  5,  7, 26],
       [ 3, 34, 30, 11]])

In [8]:
arr2[1:3,1:3]

array([[37, 18],
       [ 5,  7]])

In [9]:
arr2[1:4,1:4]

array([[37, 18,  3],
       [ 5,  7, 26],
       [34, 30, 11]])

In [10]:
arr2

array([[31,  6, 30, 30],
       [30, 37, 18,  3],
       [ 6,  5,  7, 26],
       [ 3, 34, 30, 11]])

In [11]:
arr2[arr2%2 !=0]

array([31, 37,  3,  5,  7,  3, 11])

In [12]:
student = pd.DataFrame({"id":[1,2,3] ,"Name":["Shanakr","Pratik","Prashant"], "Marks":[70, 60, 80]})
student

   id      Name  Marks
0   1   Shanakr     70
1   2    Pratik     60
2   3  Prashant     80

In [13]:
employee = pd.DataFrame({"eid":[1,2,3,4,5],"names":['A','B','C','D',np.nan],"salary":[34000,5000,60000,45000,23000],
                        "Address":["Pune", "Pune", "Mumbai", "Nasik",np.nan]})
employee

   eid names  salary Address
0    1     A   34000    Pune
1    2     B    5000    Pune
2    3     C   60000  Mumbai
3    4     D   45000   Nasik
4    5   NaN   23000     NaN

In [14]:
employee["salary"].max()

60000

In [15]:
employee[employee["salary"]== employee["salary"].max()]

   eid names  salary Address
2    3     C   60000  Mumbai

In [16]:
dataset = pd.read_csv('C:/Users/ADMIN/Desktop/FBS/Data Analysis/data set/cars93.csv')

In [17]:
dataset

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver & Passenger,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,Driver & Passenger,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,Driver & Passenger,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [18]:
dataset.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [19]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         79 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
dataset = pd.read_csv("Heart.csv")

In [22]:
dataset.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["ChestPain"] = le.fit_transform(dataset["ChestPain"])

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["Thal"] = le.fit_transform(dataset["Thal"])

In [25]:
dataset.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0,No
1,2,67,1,0,160,286,0,2,108,1,1.5,2,3.0,1,Yes
2,3,67,1,0,120,229,0,2,129,1,2.6,2,2.0,2,Yes
3,4,37,1,1,130,250,0,0,187,0,3.5,3,0.0,1,No
4,5,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1,No

In [26]:
X = (dataset.iloc[:,:-1])
y = (dataset["AHD"])

In [27]:
X

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal
0,1,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0
1,2,67,1,0,160,286,0,2,108,1,1.5,2,3.0,1
2,3,67,1,0,120,229,0,2,129,1,2.6,2,2.0,2
3,4,37,1,1,130,250,0,0,187,0,3.5,3,0.0,1
4,5,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,3,110,264,0,0,132,0,1.2,2,0.0,2
299,300,68,1,0,144,193,1,0,141,0,3.4,2,2.0,2
300,301,57,1,0,130,131,0,0,115,1,1.2,2,1.0,2
301,302,57,0,2,130,236,0,2,174,0,0.0,2,1.0,1
302,303,38,1,1,138,175,0,0,173,0,0.0,1,NaN,1

In [28]:
y

0       No
1      Yes
2      Yes
3       No
4       No
      ...
298    Yes
299    Yes
300    Yes
301    Yes
302     No
Name: AHD, Length: 303, dtype: object

In [29]:
new_data = pd.read_csv("seattleweather1948-2017_1738467795684 (1).csv")
new_data.head()

         DATE  PRCP  TMAX  TMIN  RAIN
0  1948-01-01  0.47    51    42  True
1  1948-01-02  0.59    45    36  True
2  1948-01-03  0.42    45    35  True
3  1948-01-04  0.31    45    34  True
4  1948-01-05  0.17    45    32  True

In [30]:
dataset = pd.read_csv("college_student_placement_dataset (1).csv")

In [31]:
dataset

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No
...,...,...,...,...,...,...,...,...,...,...
9995,CLG0021,119,8.41,8.29,4,No,1,8,0,Yes
9996,CLG0098,70,9.25,9.34,7,No,0,7,2,No
9997,CLG0066,89,6.08,6.25,3,Yes,3,9,5,No
9998,CLG0045,107,8.77,8.92,3,No,7,5,1,No
9999,CLG0060,109,9.41,9.77,8,No,3,5,5,No

In [32]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  object
 1   IQ                      10000 non-null  int64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  int64
 5   Internship_Experience   10000 non-null  object
 6   Extra_Curricular_Score  10000 non-null  int64
 7   Communication_Skills    10000 non-null  int64
 8   Projects_Completed      10000 non-null  int64
 9   Placement               10000 non-null  object
dtypes: float64(2), int64(5), object(3)
memory usage: 781.4+ KB

In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset["Internship_Experience"] = le.fit_transform(dataset["Internship_Experience"])

In [34]:
dataset.head()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,0,8,8,4,No
1,CLG0061,97,5.52,5.37,8,0,7,8,0,No
2,CLG0036,109,5.36,5.83,9,0,3,1,1,No
3,CLG0055,122,5.47,5.75,6,1,1,6,1,No
4,CLG0004,96,7.91,7.69,7,0,8,10,2,No

In [35]:
X = dataset[["College_ID","IQ","Prev_Sem_Result","CGPA","Academic_Performance","Internship_Experience","Extra_Curricular_Score","Communication_Skills","Projects_Completed"]]

In [36]:
y = dataset["Placement"]

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=30)

In [38]:
import tensorflow as tf